//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Blend.SampleData.PlaceDataSource
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class PlaceDataSource { }
#else

	public class PlaceDataSource : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public PlaceDataSource()
		{
			try
			{
				Uri resourceUri = new Uri("ms-appx:/SampleData/PlaceDataSource/PlaceDataSource.xaml", UriKind.RelativeOrAbsolute);
				Windows.UI.Xaml.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private PlaceList _PlaceList = new PlaceList();

		public PlaceList PlaceList
		{
			get
			{
				return this._PlaceList;
			}
		}
	}

	public class ImagesItem : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private Windows.UI.Xaml.Media.ImageSource _Image = null;

		public Windows.UI.Xaml.Media.ImageSource Image
		{
			get
			{
				return this._Image;
			}

			set
			{
				if (this._Image != value)
				{
					this._Image = value;
					this.OnPropertyChanged("Image");
				}
			}
		}

		private Windows.UI.Xaml.Media.ImageSource _Image1 = null;

		public Windows.UI.Xaml.Media.ImageSource Image1
		{
			get
			{
				return this._Image1;
			}

			set
			{
				if (this._Image1 != value)
				{
					this._Image1 = value;
					this.OnPropertyChanged("Image1");
				}
			}
		}
	}

	public class PlaceListItem : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private string _Description = string.Empty;

		public string Description
		{
			get
			{
				return this._Description;
			}

			set
			{
				if (this._Description != value)
				{
					this._Description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}

		private string _OriginalPoster = string.Empty;

		public string OriginalPoster
		{
			get
			{
				return this._OriginalPoster;
			}

			set
			{
				if (this._OriginalPoster != value)
				{
					this._OriginalPoster = value;
					this.OnPropertyChanged("OriginalPoster");
				}
			}
		}

		private double _Latitude = 0;

		public double Latitude
		{
			get
			{
				return this._Latitude;
			}

			set
			{
				if (this._Latitude != value)
				{
					this._Latitude = value;
					this.OnPropertyChanged("Latitude");
				}
			}
		}

		private double _Longitude = 0;

		public double Longitude
		{
			get
			{
				return this._Longitude;
			}

			set
			{
				if (this._Longitude != value)
				{
					this._Longitude = value;
					this.OnPropertyChanged("Longitude");
				}
			}
		}

		private Images _Images = new Images();

		public Images Images
		{
			get
			{
				return this._Images;
			}
		}

		private double _Point = 0;

		public double Point
		{
			get
			{
				return this._Point;
			}

			set
			{
				if (this._Point != value)
				{
					this._Point = value;
					this.OnPropertyChanged("Point");
				}
			}
		}

		private double _Flag = 0;

		public double Flag
		{
			get
			{
				return this._Flag;
			}

			set
			{
				if (this._Flag != value)
				{
					this._Flag = value;
					this.OnPropertyChanged("Flag");
				}
			}
		}

		private string _Address = string.Empty;

		public string Address
		{
			get
			{
				return this._Address;
			}

			set
			{
				if (this._Address != value)
				{
					this._Address = value;
					this.OnPropertyChanged("Address");
				}
			}
		}

		private string _City = string.Empty;

		public string City
		{
			get
			{
				return this._City;
			}

			set
			{
				if (this._City != value)
				{
					this._City = value;
					this.OnPropertyChanged("City");
				}
			}
		}

		private string _State = string.Empty;

		public string State
		{
			get
			{
				return this._State;
			}

			set
			{
				if (this._State != value)
				{
					this._State = value;
					this.OnPropertyChanged("State");
				}
			}
		}

		private string _Country = string.Empty;

		public string Country
		{
			get
			{
				return this._Country;
			}

			set
			{
				if (this._Country != value)
				{
					this._Country = value;
					this.OnPropertyChanged("Country");
				}
			}
		}

		private double _PostalCode = 0;

		public double PostalCode
		{
			get
			{
				return this._PostalCode;
			}

			set
			{
				if (this._PostalCode != value)
				{
					this._PostalCode = value;
					this.OnPropertyChanged("PostalCode");
				}
			}
		}
	}

	public class PlaceList : System.Collections.ObjectModel.ObservableCollection<PlaceListItem>
	{ 
	}

	public class Images : System.Collections.ObjectModel.ObservableCollection<ImagesItem>
	{ 
	}
#endif
}
